version: '3'
services:
    db:
        build: ./Database
        container_name: minitwitdb
        ports:
            - '1433:1433'

    api:
        build: ./Backend
        container_name: Backend
        ports:
            - '2222:80'
            - '2223:443'
        depends_on:
            - db
