# version: '3'
# services:
#     db:
#         build: ./Database
#         container_name: Database
#         ports:
#             - '1433:1433'

#     api:
#         build: ./Backend
#         container_name: Backend
#         ports:
#             - '2222:80'
#             - '2223:443'
#         depends_on:
#             - db

version: '3.3'

services:
    minitwitfrontend:
        build: ./Frontend
        container_name: minitwitfrontend
        depends_on:
            - backend
            - prometheus
            - grafana
        ports:
            - 3001:3001

    backend:
        build: ./Backend
        container_name: minitwitbackend
        depends_on:
            - db
            - prometheus
            - grafana
        ports:
            - '2222:80'
            - '2223:443'

    db:
        platform: 'linux/amd64'
        image: ${DOCKER_USERNAME}/minitwitdb
        container_name: minitwitdb
        ports:
            - '1433:1433'

    prometheus:
        image: prom/prometheus
        container_name: prometheus
        volumes:
            - ./prometheus.yml:/etc/prometheus/prometheus.yml
        ports:
            - '9090:9090'

    grafana:
        image: grafana/grafana:latest
        container_name: grafana
        volumes:
            - ./grafana-data/data:/var/lib/grafana
        ports:
            - '3000:3000'

    elasticsearch:
        container_name: elasticsearch
        image: docker.elastic.co/elasticsearch/elasticsearch:7.17.9
        ports:
            - 9200:9200
        volumes:
            - elasticsearch-data:/usr/share/elasticsearch/data
        environment:
            - xpack.monitoring.enabled=true
            - xpack.watcher.enabled=false
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
            - discovery.type=single-node
        networks:
            - elasticnetwork

    kibana:
        container_name: kibana
        image: docker.elastic.co/kibana/kibana:7.17.9
        ports:
            - 5601:5601
        depends_on:
            - elasticsearch
        environment:
            - ELASTICSEARCH_URL=http://104.248.101.163:9200
        networks:
            - elasticnetwork

volumes: # add this section
    elasticsearch-data:

networks:
    elasticnetwork:
        driver: bridge
    
