version: '3.3'

networks:
    main:

services:
    minitwitfrontend:
        image: ${DOCKER_USERNAME}/minitwitfrontend
        container_name: minitwitfrontend
        networks:
            - main
        depends_on:
            - backend
        ports:
            - '3000:3000'

    backend:
        image: ${DOCKER_USERNAME}/minitwitbackend
        container_name: minitwitbackend
        networks:
            - main
        ports:
            - '2222:2222'
        depends_on:
            - db

    db:
        image: ${DOCKER_USERNAME}/minitwitdb
        container_name: minitwitdb
        networks:
            - main
        ports:
            - '1433:1433'
