version: '3.3'


services:
    minitwitfrontend:
        image: ${DOCKER_USERNAME}/minitwitfrontend
        container_name: minitwitfrontend
        depends_on:
            - backend
            - prometheus
            - grafana
        ports:
            - 3001:3001

    backend:
        image: ${DOCKER_USERNAME}/minitwitbackend
        container_name: minitwitbackend
        depends_on:
            - db
        ports:
            - '2222:80'
            - '2223:443'

    db:
        image: ${DOCKER_USERNAME}/minitwitdb
        container_name: minitwitdb
        ports:
            - '1433:1433'
        volumes:
            - dbvolume:/var/opt/mssql/data

    prometheus:
        image: prom/prometheus
        container_name: prometheus
        depends_on:
            - backend
        volumes:
            - promvolume:/prometheus
            - ./prometheus.yml:/etc/prometheus/prometheus.yml
        ports:
            - '9090:9090'

    grafana:
        image: grafana/grafana:latest
        container_name: grafana
        depends_on:
            - prometheus
        volumes:
            - grafvolume:/var/lib/grafana
        ports:
            - '3333:3000'
    
    elasticsearch:
        container_name: elasticsearch
        image: docker.elastic.co/elasticsearch/elasticsearch:7.17.9
        ports:
            - 9200:9200
        volumes:
            - elasticsearch-data:/usr/share/elasticsearch/data
        environment:
            - xpack.monitoring.enabled=true
            - xpack.watcher.enabled=false
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
            - discovery.type=single-node
        networks:
            - elasticnetwork

    kibana:
        container_name: kibana
        image: docker.elastic.co/kibana/kibana:7.17.9
        ports:
            - 5601:5601
        depends_on:
            - elasticsearch
        environment:
            - ELASTICSEARCH_URL=http://104.248.101.163:9200
        networks:
            - elasticnetwork


networks:
    elasticnetwork:
        driver: bridge

volumes:
    dbvolume:
    promvolume:
    grafvolume:
    elasticsearch-data:
