---
name: Continuous Deployment Staging

on:
    push:
        # Run workflow every time something is pushed to the main branch
        branches:
            - feat/**
    # allow manual triggers for now too
    workflow_dispatch:
        manual: true

# Remember to set the following secrets in your repository's settings:
# https://github.com/your_username/itu-minitwit-ci/settings/secrets/actions
# DOCKER_USERNAME
# DOCKER_PASSWORD
# SSH_USER
# SSH_KEY
# SSH_HOST

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Login to Docker Hub
              uses: docker/login-action@v1
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v1

            - name: Build and push frontend
              uses: docker/build-push-action@v2
              with:
                  context: '{{defaultContext}}:Frontend'
                  file: ./Dockerfile
                  push: true
                  tags: ${{ secrets.DOCKER_USERNAME }}/minitwitfrontendstaging:latest
                  cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/minitwitfrontendstaging:webbuildcachestaging
                  cache-to: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/minitwitfrontendstaging:webbuildcachestaging,mode=max
                  secrets: |
                      "REACT_APP_API_URL=${{secrets.REACT_APP_API_URL}}"

                      "REACT_APP_AUTH0_DOMAIN=${{secrets.REACT_APP_AUTH0_DOMAIN_STAGING}}"
                      "REACT_APP_AUTH0_CLIENT_ID=${{secrets.REACT_APP_AUTH0_CLIENT_ID_STAGING}}"
                      "REACT_APP_AUTH0_CALLBACK_URL=${{secrets.REACT_APP_AUTH0_CALLBACK_URL_STAGING}}"
                      "REACT_APP_API_SERVER_URL=${{secrets.REACT_APP_API_SERVER_URL_STAGING}}"
                      "REACT_APP_AUTH0_AUDIENCE=${{secrets.REACT_APP_AUTH0_AUDIENCE_STAGING}}"

            - name: Build and push minitwitdb
              uses: docker/build-push-action@v2
              with:
                  context: '{{defaultContext}}:Database'
                  file: ./Dockerfile
                  push: true
                  tags: ${{ secrets.DOCKER_USERNAME }}/minitwitdbstaging:latest
                  cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/minitwitdbstaging:minitwitdbbuildcachestaging
                  cache-to: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/minitwitdbstaging:minitwitdbbuildcachestaging,mode=max

            - name: Build and push minitwitbackend
              uses: docker/build-push-action@v2
              with:
                  context: '{{defaultContext}}:Backend'
                  file: ./Dockerfile
                  push: true
                  tags: ${{ secrets.DOCKER_USERNAME }}/minitwitbackendstaging:latest
                  cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/minitwitbackendstaging:backendbuildcachcestaging
                  cache-to: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/minitwitbackendstaging:backendbuildcachcestaging,mode=max

            #- name: Test minitwit
            # run: |
            #  docker build -t $DOCKER_USERNAME/minitwittestimage -f Dockerfile-minitwit-tests .
            # yes 2>/dev/null | docker-compose up -d
            #docker run --rm --network=itu-minitwit-network $DOCKER_USERNAME/minitwittestimage
            #env:
            # DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}

            - name: Configure SSH
              run: |
                  mkdir -p ~/.ssh/
                  echo "$SSH_KEY" > ~/.ssh/minitwit.key
                  chmod 600 ~/.ssh/minitwit.key
              env:
                  SSH_KEY: ${{ secrets.SSH_KEY }}

            - name: Deploy to server
              # Configure the ~./bash_profile and deploy.sh file on the Vagrantfile
              run: >
                  ssh $SSH_USER@$SSH_HOST
                  -i ~/.ssh/minitwit.key -o StrictHostKeyChecking=no
                  '/minitwit/deploy.sh'
              env:
                  SSH_USER: ${{ secrets.SSH_USER }}
                  SSH_HOST: ${{ secrets.SSH_HOST_STAGING }}
